project_name: codeql-action-sync

builds:
  - goos: [linux, darwin, windows]
    goarch: [386, amd64, arm64]
    ldflags:
      - -X github.com/github/codeql-action-sync/internal/version.version={{.Version}}
      - -X github.com/github/codeql-action-sync/internal/version.commit={{.Commit}}
