allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - mit
  - unlicense

ignored:
  go:
    - golang.org/x/**/*
    - github.com/ProtonMail/go-crypto/**/* # A fork of golang.org/x/crypto/openpgp.
